language: cpp

os:
    - osx
    
compiler:  
    - gcc
    - clang

before_install:
  - brew update
  - brew install insighttoolkit
  
before_script:
    - mkdir build
    - cd build
    - cmake ../src

script: make  
