language: cpp

os:
    - osx
    
compiler:  
    - gcc
    - clang

before_install:
  - brew tap homebrew/science
  - brew install insighttoolkit --with-gdcm --build-from-source
  
before_script:
    - mkdir build
    - cd build
    - cmake ../src

script: make  
