language: cpp

os:
    - osx
    
compiler:
    - clang

before_install:
  - brew tap homebrew/science
  - brew install vtk insighttoolkit
  
before_script:
    - mkdir build
    - cd build
    - cmake ../src

script: make -j2
